input:
  towards_future: false
  ignore_config: false
  req_count: 200
  loops: 20
  influencers: [
      "AlertTrade",
      "whale_alert",
      # "intocryptoverse",
      # "TheMoonCarl",
      # "TheCryptoLark",
      # "BTCFoundation",
      # "ethereum",
      # "Cardano",
      # "AltcoinDailyio",
      # "StackerSatoshi",
      # "maxwell_maher",
      # "100trillionUSD",
      # "coinbureau",
      # "CryptosRus",
      # "elonmusk",
      # "VitalikButerin",
      # "ErikVoorhees",
      # "barrysilbert",
      # "TimDraper",
      # "SatoshiLite",
      # "brian_armstrong",
      # "FEhrsam",
      # "aantonop",
      # "bhorowitz",
      # "rogerkver",
      # "APompliano",
      # "TyDanielSmith",
      # "ToneVays",
      # "CryptoCobain",
      # "CryptoWendyO",
      # "StackingUSD",
      # "Girlgone_Crypto",
      # "EuclidAndOaks",
      # "CryptoEuclid",
      # "Mysticaloaks",
      # "officialmcafee",
      # "davidgokhshtein",
      # "justinsuntron",
      # "IvanOnTech",
      # "KennethBosak",
      # "CryptoBrekkie",
      # "TheCryptoDog",
      # "Bitboy_Crypto",
      # "DanHeld",
      # "PeterMcCormack",
      # "LayahHeilpern",
      # "coinbound_io",
    ]
